# Site settings
title: FSeq
version: 0.1.7
email: mail@getfseq.com
description: Just a simple, single page responsive template brought to you by HTML5 UP.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.lasselauch.com/" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
# download_button_url: "https://lasselauch.lemonsqueezy.com/checkout/buy/981edfe2-cf03-48f1-a77e-11e0574ac4ce"
# Social settings
github_url: https://github.com/lasselauch/FSeq-Home
twitter_url: https://twitter.com/lasse_lauch

# Build settings
markdown: kramdown